version: '3'

services:
  mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
